### ISSUE TITLE
Density - Publish 1.1 with PhET-iO Upgrades

### ISSUE THREAD

**Issue by markgammon** [phetsims/density#108]
As part of the "batch release" milestone https://github.com/orgs/phetsims/projects/44, publish Density, for brands=phet,phet-io.

**Comment by arouinfar** [comment]
As of 4/3/23, these appear to be the only outstanding issues before moving Density into QA:

- #154 
- #133 
- #50 
- https://github.com/phetsims/density-buoyancy-common/issues/76

**Comment by arouinfar** [comment]
Density 1.0 is currently listed in the PhET-iO Simulations spreadsheet as "PhET-iO Studio with future migration support". However, the link to the simulation was never published, and only one partner currently has access to it. According to @kathy-phet we do not need to support migration to the 1.1 version, so no migration rules are necessary.

Here's the relevant discussion in the phet-io Slack channel (from ~2 months ago), with the partner name redacted:

>Sam Reid
>Greetings!  We noticed that density is listed as “PhET-iO Studio with future migration support” but it also does not have a URL issue listed. So we wanted to check on that.  Is it missing the URL?
>
>Amy Rouinfar
No, the lack of a URL was intentional at the time, but is worth reconsidering. Density was published right as we started a lot of the Studio improvements, and we delayed publishing the URL thinking the batch release would kick off  “any day now”. The latest version of Density might support some of the more modern Studio features, but not all.
>
>Amy Rouinfar
>Also, I’m not sure if QA fully tested PhET-iO or not.
>
>Sam Reid
>I feel the question about whether we need to support migration is: “do we have a client that is using the old version that we want to support migrating to a newer version?”
>
>Amy Rouinfar
>I am pretty sure that {{partner name}} has access to it currently (not because we gave it to them, but because they saw it in the spreadsheet and followed the standard URL pattern to get to it). I don’t think we are supporting migration, but Kathy should confirm.
>
>Kathy Perkins
>We published it, but I didn't put the URL because we decided we needed to add the improvements around customization. {{parner name}} asked for the URL, so I gave it to them but with the caveate that we needed to republish it. We aren't supporting migration.
>
>Kathy Perkins
>QA did fully test PhET-iO of Density at the time - but lots of changes since.

**Comment by arouinfar** [comment]
4/19/23 dev test created 
* https://github.com/phetsims/qa/issues/930

4/23/23 dev testing completed

**Comment by arouinfar** [comment]
5/11/23 rc.1 created
* https://github.com/phetsims/qa/issues/942

**Comment by arouinfar** [comment]
6/4/23 rc.2 (spot check) created
* https://github.com/phetsims/qa/issues/953

6/5/23 testing completed

**Comment by arouinfar** [comment]
6/6/23 Density 1.1 was published.
