### ISSUE TITLE
Instruction in Example Guide may describe wrong behavior

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/density#135]
**Device**
Dell
**OS**
Win 11
**Browser**
Chrome
**Problem Description**
For https://github.com/phetsims/qa/issues/820
Under the section for Mass Properties under the mystery screen, it says this:

> To set the mass, use the massProperty. When customizing the mass, the volume will remain constant and the material/density will be updated.

However, the volume seems to change and the density is kept constant instead. I'm not sure if this is an issue with the guide or with the behavior, so assigning @arouinfar as well as @jonathanolson.

**Visuals**
<img width="751" alt="instructionswrong" src="https://user-images.githubusercontent.com/41024075/180075841-39534f0d-987a-45f0-85c6-2f638c552c02.png">
![volumedown](https://user-images.githubusercontent.com/41024075/180075847-1ba0996d-0a0e-4237-a95e-8bde2b1342f7.gif)

**Comment by arouinfar** [comment]
@jonathanolson this isn't the intended behavior, and the Examples doc is consistent with the `phetioDocumentation` of the `massProperty` which states:
> Current mass of the block. Changing the mass will result in changes to the material (and therefore density), but the volume will remain the same.

**Comment by jonathanolson** [comment]
My impression was the intended behavior is for the volume to update when mass is changed (especially for phet-io changes). Is that the desired behavior for this?

Work for https://github.com/phetsims/density/issues/101 notes the desire to change the volume, and the Mystery screen has the option `adjustMassWithVolume` set to true.

If that's not the desired behavior, it might be a significant amount of work.

**Comment by arouinfar** [comment]
Thanks @jonathanolson, I was mistaken. I've updated examples.md to describe the correct behavior.

Due to the changes made in #138 to set `volumeProperty.rangeProperty` to [1, 10] L, if users aren't careful when setting `massProperty` they could create a situation where `volumeProperty` becomes out of range causing the sim to reload.

For example:
1. Set `customDensityProperty` to 10000 kg/m^3
2. Set `massProperty` to 1000 kg
3. The required volume is 100 L, which is out of range.
     <img width="300" alt="image" src="https://user-images.githubusercontent.com/8419308/186990023-8bbbc558-bb0f-4e96-964b-42946ce218b2.png">
4. When the sim reloads, the `massProperty` becomes 100 kg which corresponds to the maximum allowed volume (10 L).

It seems like Studio otherwise restores the state correctly, so users are unlikely to lose their work. I think we made the right call in #138, so I added further clarification to examples.md for this case.
