### ISSUE TITLE
Update `phetioDocumentation` of block `massProperty`

### ISSUE THREAD

**Issue by arouinfar** [phetsims/density#152]
For #150 

In https://github.com/phetsims/density/issues/126 the `phetioDocumentation` of several elements was updated, including `massProperty`.

Current documentation for a block's `massProperty`:
>Current mass of the block. Changing the mass will result in changes to the material (and therefore density), but the volume will remain the same.

This is mostly inaccurate. The behavior depends on the screen. On Intro and Mystery, changing the mass will change the volume, keeping the density constant. The Compare screen behaves differently. The mass can be directly changed only for the "Same Mass" set of blocks. There, changing the mass will change the density (volume kept constant). 

@jonathanolson is it possible to have different documentation on different screens? If not, let's use this instead:

> Current mass of the block. Changing the mass will result in changes to the volume (Intro and Mystery Screens) or density (Compare Screen).

**Comment by arouinfar** [comment]
@samreid I think this is an issue you could handle, so I'm co-assigning you. Please let me know if you have any questions.

**Comment by samreid** [comment]
Yes, the documentation can be different on each screen. However, in this case I feel it is preferable to have the same documentation since it is the same type of object in each screen and that it just behaves differently based on context. For instance, it would be confusing for a client to read the `massProperty` documentation on one screen and assume it meant the same thing everywhere.  So I'll use the "let's use this instead" text.  But please reassign @jonathanolson if it is more important to give different text on the different screens.

**Comment by arouinfar** [comment]
> For instance, it would be confusing for a client to read the massProperty documentation on one screen and assume it meant the same thing everywhere.

Excellent point @samreid. I agree.

>  So I'll use the "let's use this instead" text. 

Thanks, looks good in master, closing.
