### ISSUE TITLE
Reviewing Density PhET-iO example 

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/density#158]
I already go throw all the [Example document ](https://github.com/phetsims/phet-io-sim-specific/blob/master/repos/density/examples.md) and everything is very well understandable!

I notice just one issue: 
In specify block mass - Mystery
I think we already talked about this, user can build blocks of any size by changing its mass (no limited to the 1 - 10 L):
![image](https://user-images.githubusercontent.com/26031501/228978223-dbd19e7f-f8a4-4d2a-8365-88f79d883af4.png)

If that is ok, and that is the reason of the text “Note that volume must be 1-10 L, so take care that the customized massProperty results in a volume within this range”, then you can close this issue.

Thanks!

**Comment by arouinfar** [comment]
Tagging #151.

Thanks @DianaTavares! 

> If that is ok, and that is the reason of the text “Note that volume must be 1-10 L, so take care that the customized massProperty results in a volume within this range”, then you can close this issue.

Unfortunately, this is a known issue reported in https://github.com/phetsims/density/issues/154. I included the warning so that clients are aware. PhET-iO has the power to create problematic situations, but we generally follow the principle of "customize wisely" and this is not a wise customization. :)
