### ISSUE TITLE
User suggestion: units, hide volume

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/density#21]
> We thought your simulation could be improved in two ways.  One use mL and grams not liters and kilograms.  Such large values seem unrealistic for school laboraatory activity.  Second  It would be nice if you not give the volume of the sample, rather let students find the value by the difference in the water level.

**Comment by DianaTavares** [comment]
> We thought your simulation could be improved in two ways. One use mL and grams not liters and kilograms. Such large values seem unrealistic for school laboraatory activity.

I think that the units in the sim are good. And students can use laboratory activities to transform between units. 

> Second It would be nice if you not give the volume of the sample, rather let students find the value by the difference in the water level.

that is the goal of the mystery screen.

**Comment by oliver-phet** [comment]
Just documenting another email:

> our students use SI for volume ( not liters but m3 ). Maybe some countries too. Is it possible on the HTML5 version for basin in   Density  and    Buoyancy  ( as well for table Densities  of Various Materials for   Density) to add such this option ?

**Comment by DianaTavares** [comment]
It was discussed in the design meeting that we can do something with a query parameter that changes the units of the simulation to kg/m3 (that is the same number that g/l).

**Comment by DianaTavares** [comment]
In today's design meeting we discuss this possibility for density and buoyancy. Looks like a good option, but not easy to implement and apport to the users. In the case of the units that have a, as a result, the same density value (for example kg/L, g/cm3, and g/ml) @jonathanolson  commented that can be dangerous to only modify the units and leave the numbers and visualizations as the same.  The students can get confused that a block with a mass of 1 kg looks the same in the simulation that a block of 1 gr.  

The other option presented was to change units and convert the values displayed, for example, if the original value was 1 L, then in m3 to display 0.001 m3, that mean more decimals, more difficult operations for the students to perform, and it can present difficulties with the steps in the sliders. 

Then for the actual density and buoyancy design, this request is not going to be considered.

**Comment by arouinfar** [comment]
@DianaTavares has already nicely explained why we haven't added support for g/mL or kg/m<sup>3</sup>, but I would like to summarize:

> One use mL and grams not liters and kilograms. Such large values seem unrealistic for school laboraatory activity. 

Density is not intended to replicate the traditional laboratory experience. Using g and mL is not realistic in this simulation. We would need to multiply the mass and volume values by a factor of 1000, making the values incredibly large and difficult to work with. However, by providing density in kg/L, the values will match those students familiar with g/mL are accustomed to. (Water has a density of 1 in both kg/L and g/mL).

> our students use SI for volume ( not liters but m3 ). Maybe some countries too. Is it possible on the HTML5 version for basin in Density and Buoyancy ( as well for table Densities of Various Materials for Density) to add such this option ?

The underlying model uses m<sup>3</sup> as the volume unit, but it is unsuitable for the view. The volume values would become incredibly small and difficult to work with. However, in #147 we added support to display the volume units in dm<sup>3</sup> instead of L. This is a bit of a compromise. The units will appear more familiar, but the values will remain unchanged.

> Then for the actual density and buoyancy design, this request is not going to be considered.

Agreed, but since we are not making changes other than #147, we should close this issue.
