### ISSUE TITLE
Small blocks don't bounce and look odd

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/density#67]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Firefox
**Problem description**
For https://github.com/phetsims/qa/issues/663. May be connected to https://github.com/phetsims/density/issues/37 and/or https://github.com/phetsims/density/issues/33.
When you drag a large block with a small density to the bottom of the pool and let go, it shoots up and bounces a bit. This looks alright and seems to behave fine. However, if the block is a smaller size with the same density, they move up and stop more abruptly, and it looks a bit odd.

**Visuals**
![nobounceoddlook](https://user-images.githubusercontent.com/41024075/124659347-16772380-de62-11eb-9870-5475981137c6.gif)
![nobounce](https://user-images.githubusercontent.com/41024075/124659353-1840e700-de62-11eb-8601-597fb3db1274.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Density‬
URL: https://phet-dev.colorado.edu/html/density/1.0.0-dev.16/phet/density_all_phet.html
Version: 1.0.0-dev.16 2021-06-22 15:36:28 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0
Language: en-US
Window: 1280x675
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by DianaTavares** [comment]
you are right, it looks very strange. I am playing with the prototype version of the website and it has a better behavior respected to this. I think that probably was some modification related to #37 and/or #33. @jonathanolson, can you review it?

**Comment by jonathanolson** [comment]
I've added three query parameters above:

```js
  // Controls the proportional amount of overall result viscosity forces applied
  viscosityMultiplier: {
    type: 'number',
    defaultValue: 1
  },

  // A mix between 0: Full viscosity is applied when any part of a mass is in the liquid, 1: The viscosity effect is
  // multiplied times the proportion of the mass submerged (lowering viscosity when partially submerged).
  viscositySubmergedRatio: {
    type: 'number',
    defaultValue: 0
  },

  // Viscosity for masses larger than this will be reduced to the force for this viscosity (somewhat of a hacK)
  viscosityMassCutoff: {
    type: 'number',
    defaultValue: 2
  }
```

I demoed effectively `viscosityMultiplier=2&viscositySubmergedRatio=0.8`. @DianaTavares what query parameter combinations seem to work best for you?

**Comment by DianaTavares** [comment]
I already play with the parameters and the one that I like most how to generate the bouncing was viscosityMassCutoff. I use the value of 0.5 like it is in[ this link](https://bayes.colorado.edu/dev/phettest/density/density_en.html?ea&brand=phet&viscosityMassCutoff=0.5) and I like the behavior for small and big blocks with low density in water:
![density1](https://user-images.githubusercontent.com/26031501/127240298-b94f6a56-52a1-4043-ac27-9b975d6ba76d.gif)

**Comment by DianaTavares** [comment]
by slack @jonathanolson commented that it used to be the previous value before it was changed based on one of the issues #37. Reviewing the comments in that issue @arouinfar  and I agree that the behavior was acceptable, and we can use viscosityMassCutoff as 0.5. But this opens a problem with the common code between Density and Buoyancy because the behavior of low dense blocks in fluids with high density has issues. Like is shown in the gif, the less dense fblock starts to bounce by itself: 
![Buoyancy](https://user-images.githubusercontent.com/26031501/127363689-dc0787f6-a168-40c7-a774-bf4065aef7f7.gif)

@jonathanolson suggests finding a solution that fits both sims. And some of the options are:
1. Have different viscosity values for dense fluids in buoyancy
2. Limit the density that the blocks can have. If we restrict the block mass to 0.5 kg, the block in the exploring screen have a good behavior (it doesn't bounce bai itself):
![image](https://user-images.githubusercontent.com/26031501/127364308-b6a47192-36d8-44f5-bdc5-1e622f669159.png)

the problem is that not only does the explore screen allows objects with super small density. The empty bottle gets lost in the Applications screen with the denser fluid: 

![image](https://user-images.githubusercontent.com/26031501/127364457-16b79ac7-3f93-462a-8c9d-b569b459a585.png)

My suggestion is to add in this situation a "return object" pop op screen probably. because we are not going to find a value that works for all the cases, with a sim ta allow so extreme values.

**Comment by DianaTavares** [comment]
During the last design meeting, it was discussed the idea to limit the max velocity that a block can get when it goes out of the water, making that denser blocks go faster to the equilibrium.   @jonathanolson  is going to play with that option.

**Comment by jonathanolson** [comment]
I limited the max velocity to 5. @DianaTavares can you try it out?

**Comment by DianaTavares** [comment]
It works perfectly for Density! I think that the behavior for the Explore screen in Buoyancy is very good, but in the bottle screen still jumping the bottle for a long time. 

![Bottel](https://user-images.githubusercontent.com/26031501/128350697-f9432083-79c5-45ed-be5b-41bb38b018ec.gif)

I think that this behavior is acceptable and we can go with these values. I just want to present it today in the design meeting for second voices.

**Comment by DianaTavares** [comment]
In the design meeting, we agree that this behavior is good! 
Use viscosityMassCutoff as 0.5 to allow small blocks to bounce, and limited the max velocity to 5 to make less dense blocks to stabilize faster.

**Comment by jonathanolson** [comment]
Implemented the cutoff, can you verify things look good?

**Comment by DianaTavares** [comment]
it is looking perfect, thanks!!
