### ISSUE TITLE
Move mass labels on the block behind the water

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/density#71]
In the actual sim the labels of the block's mass are in front of the water: 
![image](https://user-images.githubusercontent.com/26031501/127224807-b6437d26-5b51-4e7b-8225-bedf3a2b726a.png)

@kathy-phet  commented that sometimes having them in front of the water messes up my perspective of going into the water.  It is not hard to test it, then let's try to mother the mass labels behind the water.

**Comment by jonathanolson** [comment]
This is possible, but tricky and ill-defined in cases like this:
![image](https://user-images.githubusercontent.com/480878/127259488-e6c6814c-0f8b-4e0d-a14f-3a5f0240a048.png)

We'd need to embed the label in the 3D scene in order to have it behind water (especially the water top).

If we embed it, it would need to appear in front of the ground, but behind the water (tricky), since this label would be sticking into the ground. We'd need to make them smaller and tweak a lot of things.

Thoughts @DianaTavares @kathy-phet?

**Comment by kathy-phet** [comment]
It sounds hard and tricky, so I don’t think we so do anything.

**Comment by kathy-phet** [comment]
@DianaTavares - Should we just close this?

**Comment by DianaTavares** [comment]
yes! I had the first interview and the student didn't mention anything related to it.
