### ISSUE TITLE
Potential floating point issues with mass and volume

### ISSUE THREAD

**Issue by arouinfar** [phetsims/density#92]
For #76 

On startup, `density.exploreScreen.model.primaryMass.massProperty` is 1.2000000000000002 kg and `density.exploreScreen.model.primaryMass.volumeProperty` is 0.0030000000000000005. These values are not an exact match of the data provided in the panel:
![image](https://user-images.githubusercontent.com/8419308/131404225-e9f15293-9d4a-4db1-b1a4-af40b27ba5f2.png)

The density of wood in the model is 400 kg/m^3. I'm not sure how the primary mass is created on startup, but its starting mass/volume divides nicely. It looks like there may be some floating point issues.

I see a similar issue when looking at `density.introScreen.model.sameMass.*Mass.massProperty`. Presumably, these blocks should have been instantiated with a mass of exactly 5.00 kg, but the the value displayed in Studio is 5.000000000000003 kg.

In situations where the mass or volume is set with a slider, the model value should be an exact match of the what is displayed in the view. In situations where changing the mass also changes the volume, it's understandable if the derived value differs from the displayed value, though.

**Comment by jonathanolson** [comment]
Is this a studio issue, or a general one? If we need this level of exactness internally (and in the reported API), then we shouldn't be using floating-point numbers, but instead code or a library that handles exact values (symbolically, since we'd need cube roots). To me, it potentially makes sense to live with this, or to round the values shown in the studio.

It sounds somewhat generally helpful to have some math systems that are more accurate, is this worth investigation? (I've run into issues helping others or with other sims where floating point numbers might not be the ideal representation).

**Comment by arouinfar** [comment]
We spoke about this some at a recent design meeting. Due to the inter-connected nature of the variables, it's not particularly straightforward to set the mass/volume to the exact values in the display. I'll go ahead and close this one @jonathanolson.
